### ISSUE TITLE
Improvements to `backend` methods

### ISSUE THREAD

**Issue by renatomello** [qiboteam/qibo#1023]
Right now, `backend.calculate_norm` calculates one specific norm, which is the Frobenius (aka Hilbert-Schmidt) norm.

So, there are two possibilities here:

1. Give the method more flexibility to calculate different norms (e.g. [numpy.linalg.norm](https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html))
2. Rename the method to specify the only norm that calculates

Another thing is, since the Hilbert-Schmit inner product between two operators is the HS norm squared, we could use `backend.calculate_norm` to replace `backend.calculate_overlap` and `backend.calculate_overlap_density_matrix` entirely.

Moreover, `backend.entanglement_entropy` is now redundant with `qibo.quantum_info.entanglement_entropy`.
```[tasklist]
### Tasks
- [ ] https://github.com/qiboteam/qibo/pull/1043
- [ ] https://github.com/qiboteam/qibo/pull/1044
- [ ] https://github.com/qiboteam/qibo/pull/1045
```

**Comment by renatomello** [comment]
@stavros11 @scarrazza Now that I am looking at it, there is a bigger problem here: `backend.entanglement_entropy` is *not* calculating [Entanglement Entropy](https://en.wikipedia.org/wiki/Entropy_of_entanglement) between two partitions of a quantum system (see `qibo.quantum_info.metrics.entanglement_entropy`). It is instead calculating "just" the [von Neumann entropy](https://en.wikipedia.org/wiki/Von_Neumann_entropy) of a quantum system (see `qibo.quantum_info.metrics.entropy`).

**Comment by stavros11** [comment]
> @stavros11 @scarrazza Now that I am looking at it, there is a bigger problem here: `backend.entanglement_entropy` is _not_ calculating [Entanglement Entropy](https://en.wikipedia.org/wiki/Entropy_of_entanglement) between two partitions of a quantum system (see `qibo.quantum_info.metrics.entanglement_entropy`). It is instead calculating "just" the [von Neumann entropy](https://en.wikipedia.org/wiki/Von_Neumann_entropy) of a quantum system (see `qibo.quantum_info.metrics.entropy`).

Indeed, as far as I remember this function was written only for the `EntanglementEntropy` callback, which is calling the partial trace in a previous step
https://github.com/qiboteam/qibo/blob/51233c289116217c6a33f168031042c56ad3010d/src/qibo/callbacks.py#L122
I guess that's the difference you mean. Maybe the name in `backend.entanglement_entropy` was not the best choice.

> Besides that, since the functions in `qibo.quantum_info` are backend-agnostic, do we even need to keep this method?

If it is possible to replace it with some other existing method then we don't need to keep both. We should avoid repetition as much as possible.

**Comment by renatomello** [comment]
> If it is possible to replace it with some other existing method then we don't need to keep both. We should avoid repetition as much as possible.

I'll try to implement this callback using `qibo.quantum_info.entanglement_entropy` so then we can remove these redundancies.
