### ISSUE TITLE
Product formulas for Hamiltonian simulation

### ISSUE THREAD

**Issue by shangtai** [qiboteam/qibo#1242]
Had a discussion with @marekgluza  and it is relevant to issue #1138 

Let's add a new method to symbolic hamiltonian where we can apply the product formula, mainly to implement eqs (1-2) here https://arxiv.org/abs/1901.00564 

The idea is that given a symbolic Hamiltonian H,  we find a corresponding  circuit of primitive gates that approximates the evluate to time t up to eps as arguments. This would help to explore use of fewer gates to achieve the approximation.

To do this, I think we also need the ability to split the Hamiltonian into groups which contains commuting elements. It would be great if someone has coded this part.

**Comment by marekgluza** [comment]
Hamiltonian simulation task

- cf abstract stage in #1138 
   - [ ]  Given a symbolically prescribed $H_0=\sum h_i$ get a circuit approximation of $e^{itH_0}$ via a product formula for example first order $(\prod_i e^{i t/N h_i})^N$

- More specific definitions we wish to approximate 
$$ U(t) = $e^{itH_0}$$
using parametrized gates
$$U_i(s) = e^{i s h_i})$$
For this we define the first order formula
$$L_N(t) = (\prod_i e^{i t/N h_i})^N$$
For any given $\epsilon >0$ we wish to find $N$ such
$$\|L_N(t) - U(t)\|\le \epsilon$$
in operator norm.

## Stage 1: Strategies for finding $dt$ to hit $\epsilon$ for the first order product formula

### Scenario A: Classical simulation is possible. 
This is the case where we can use the numpy backend to compute and store $U(t)$
This function defines $N$ by an exponential growth so that at some point the criterion above is fulfilled.
https://github.com/qiboteam/qibo/blob/0eb381d8644a74647501a196d2533d406c7b2d51/src/qibo/models/dbi/double_bracket_evolution_oracles.py#L81-L116

- [ ] Task: find smallest needed $N$.
  - [ ] implement binary search to extend the function above
  - [ ] make the procedure more efficient
    - [ ] perform slicing $U(t) = U(t_1)U(t_2)\ldots U(t_K)$ so that not too many circuit multiplications are needed
     - [ ] or diagonalize etc but basically we will take powers of $Q(s) = (\prod_i e^{i s h_i})

**Comment by marekgluza** [comment]
Non-trivial benchmark example:

A hamiltonian of the form
$$H_0 = \sum_i (Z_i + X_iX_{i+1} + X_i Z_{i+1} X_{i+2})$$
can be simulated by free fermions for 10k sites. We can probe the performance there.

@shangtai 
- [ ] verify that in the notation above $h_i = (Z_i + X_iX_{i+1} + X_i Z_{i+1} X_{i+2})$. This is my question related to https://arxiv.org/abs/1901.00564 whether the notation there is useful for us or should we adapt it? In this example, can we use their higher order formula?

**Comment by marekgluza** [comment]
### How this connects to existing capabilities

See same function again:
https://github.com/qiboteam/qibo/blob/0eb381d8644a74647501a196d2533d406c7b2d51/src/qibo/models/dbi/double_bracket_evolution_oracles.py#L81-L116

It assumes that we have a `SymbolicHamiltonian` for $H_0$ which can generate circuit.
In the notation above, that circuit is exactly $Q(s)$ so the `circuit` method of `SymbolicHamiltonian` should be used only once and for a small step size. The rest should be by taking a concatenation of $N$ such circuits.

@shangtai Once the PR is in review I will spend more time on how to use Higher order formulas in this formalism but I believe it's just directly same as Childs and Su. In fact I formulated the above with parametrized gates (which we can obtain from a universal gate set by Solovay-Kitaev) and they just assume they have the exponentials $e^{it h_j}$. Then in terms of these parametrized gates the higher order formulas are formulated.
No splitting into even and odd is needed here.

- [ ] explore the advantage of having an even - odd splitting of terms. Inside of each group all the terms are commuting and hence can be implemented in parallel. Does it matter for decoherence?

**Comment by marekgluza** [comment]
## Stage 2: higher order formulas for Hamiltonian simulation for `SymbolicHamiltonian`

To be expanded: Discussion how to use existing capabilities and integrate with the CS19 paper

**Comment by marekgluza** [comment]
Could be considered: https://arxiv.org/abs/2403.08729
