### ISSUE TITLE
Distributed circuit missing features

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibo#130]
The current multi-GPU supports only custom gates and therefore it does not have the following features:

- [ ] Density matrices: can be added once #129 is fixed.
- [ ] Noisy simulation / errors: can be done either with density matrices (takes more memory) if #129 is fixed or without (takes more time) if #91 is fixed.
- [ ] Automatic gradients: can be added once #126 is fixed.
- [ ] Compilation: depends on whether we decide to allow compiling the custom operators (currently disabled).

All these features are available in the single device circuits **only** if the old (slow) tensorflow gates are used.
